version: '3.9'
services:
  mongo:
    image: mongo:7.0.2
    container_name: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    networks:
      - default
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  mongo-express:
    image: mongo-express:1.0.0-20-alpine3.18
    container_name: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    networks:
      - default
    volumes:
      - data:/data
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@mongo:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASS}

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local